# Generated by Django 3.1.1 on 2020-10-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quienes_somos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriasGaleria',
            new_name='QuienesSomos',
        ),
    ]
