# Generated by Django 3.1.1 on 2020-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=250)),
                ('telefono_adicional', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('horario', models.TextField()),
                ('calle', models.CharField(max_length=250)),
                ('numero_exterior', models.CharField(max_length=250)),
                ('municipio', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('pais', models.CharField(max_length=250)),
                ('codigo_postal', models.CharField(max_length=250)),
            ],
        ),
    ]
