# Generated by Django 3.1.1 on 2020-09-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasGaleria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_slider', models.FileField(upload_to='inicio/images/')),
                ('nombre_primer_servicio', models.CharField(max_length=50)),
                ('descripcion_primer_servicio', models.TextField(max_length=250)),
                ('nombre_segundo_servicio', models.CharField(max_length=50)),
                ('descripcion_segundo_servicio', models.TextField(max_length=250)),
                ('nombre_tercer_servicio', models.CharField(max_length=50)),
                ('descripcion_tercer_servicio', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenGaleriaInicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='inicio/images/proyectos/')),
                ('nombre', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inicio.categoriasgaleria')),
            ],
        ),
    ]
