# Generated by Django 3.1.1 on 2020-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_arkos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SistemaArkos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CategoriasGaleria',
        ),
    ]
