# Generated by Django 3.1.1 on 2020-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='link_descarga',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
